name: graphus
description: Chart app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  auto_route: ^5.0.4
  flutter:
    sdk: flutter
  math_parser: ^1.5.0
  reactive_color_picker: ^0.4.0
  reactive_forms: ^14.1.0

dev_dependencies:
  analyzer: ^5.4.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  zekfad_lints: ^1.2.0

flutter:
  uses-material-design: true
